### ISSUE TITLE
Dynamic visualization in cytoscape

### ISSUE THREAD

**Issue by jsaucerman** [saucermanlab/Netflux#11]
Do we have the updated code for dynamic cytoscape visualization on this repository? If not we need to update this and then update the documentation.

**Comment by mdsutcliffe** [comment]
I don't think it's on this repository, but it should be on the lab server under my name -> Cytoscape App Development (or similar). My access to the lab server was removed, but someone should be able to get the code.

**Comment by jsaucerman** [comment]
Great thanks Matt we'll check on that.

**Comment by jsaucerman** [comment]
In the documentation, we've replaced the previous use of the dynamicExpression toolbox or modified versions of CyAnimator with using the current public version of CyAnimator. dynamicExpr.jar was removed.
https://github.com/saucermanlab/Netflux/commit/6136c550ebc8dd739f46417c813355122de7cefe
